name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Bun version from .prototools
        id: get-bun-version
        run: echo "BUN_VERSION=$(grep -oP 'bun = "\K[^"]+' .prototools)" >> $GITHUB_ENV

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies
        run: bun install

      - name: Check formatting
        run: bun check-format

      - name: Lint
        run: bun lint

      - name: Run tests
        run: bun ci

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: lorenzh/coin-ctrl
